# Generated by Django 3.0.5 on 2020-05-02 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='lis_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 2, 22, 36, 40, 676294)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
